name: patientapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.2.0
  firebase_core: ^1.0.3
  google_fonts: ^2.2.0
  carousel_slider: ^4.0.0
  http: ^0.13.4
  get: ^4.6.1
  fluttertoast: ^8.0.8
  intl: ^0.17.0
  dropdown_button2: ^1.1.1
  flutter_switch: ^0.3.2
  animated_horizontal_calendar: ^0.0.2
  date_util: ^0.1.4
  cloud_firestore: ^3.1.8
  path:
  font_awesome_flutter:

  #date_util: ^0.1.4
  otp_text_field: ^1.1.1
  pin_code_fields: ^7.3.0
  expandable: ^5.0.1
  basic_utils:
  otp_autofill: ^2.1.0
  razorpay_flutter: ^1.2.9
  image_picker: ^0.8.4+4
  url_launcher: ^6.0.20
  flutter_rating_bar: ^4.0.0
  rating_dialog:
  sms_autofill: ^2.2.0
  firebase_storage: ^10.2.7
  dio:
  alt_sms_autofill:
  grouped_buttons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_launcher_icons: ^0.9.2

# flutter_icons:
#   image_path: "icon/icon.png" 
#   android: true
#   ios: true

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/