import 'package:flutter/material.dart';
const white = Colors.white;
const black = Colors.black;
const col1 = Color(0xFF11BFF1);
const col2 = Color(0xFF28318C);
const col3 = Color(0xFF6A6A6A);
const col4 = Color(0xFF11BFF1);
const col5 = Color(0xFF6A6A6A);
const col6 = Color(0xFFF0F0F0);
const textFieldColor = Color(0xFFF3F3F3);
const hinttextColor = Color(0xFFABABAB);